notifications:
  email: false
sudo: false
language: python
matrix:
  fast_finish: true
cache:
- pip
python:
- '2.7'
- '3.5'
before_install:
- travis_retry pip install --upgrade pip setuptools py coveralls
install:
- travis_retry pip install -e .[tests]
- pip freeze
script:
- "./run-tests.sh"
after_success:
- coveralls
deploy:
  matrix:
  - provider: pypi
    user: inspirehep
    distribution: sdist
    password:
      secure: APR4ShTKDPWeMlHDBkKdhg0ZrU/DPA6uxt+damGBSNxKy/FPsOs3uKue5KdEIELWG4rudwtKQ41a86Eq9it7oediQ5zNnag5Wapy2gFR0+jTC7rSXarUPfwavPV+rLPpfrITj2pUmtBNYUtKRyq08J8Z4bSFmFJWZflJvB8rZ/MONG9/NybtggHQll5M4LfU2mcOU9XDOTPsgnUR7ku/9YlvcZxwXoWlwvavnkE6WgDESrQwKIholyg4P28DNRe0XpoaX/laVdFdFuzGl6H3r2iNLXyDKHTy243F5pTE/jA00bQkkk3/Po66kEvt8aht9mBlKSrSCKBL9fstVRWTKhQYKwXEZh28fFNlZmmyXPBx+4KTwrCkRPBjuKQpvARXW3+kmbfNPyBoRXWndVVcCz7kmszJF53L2akIO5thucMdbhsFHxt4EX6z5aZX0mK9RvpMZ1NwWF+wcP73/FJJNigyemUDPAbPeJNI7bd+mtLsuikpbQ2hxhpZ25YRF+io5ptMibJMOSLF/VokLacT+W2iGipJGnEs8rxyDCKjGjNxC8O/q3J5MQF2sQnrkjr8ZHGPTA83m3jqxzK7uGK5fMgu0dTxV706PDljGmSNfkHLr2i5i/EtlJ1pQyE90Kyt/IcAb6As4vesIYHbsQ1w23hhs77djXPQmkiZqQbZ7Os=
    on:
      branch: master
      python: '2.7'
